### ISSUE TITLE
Error in clienv$num_colors[[std]] : subscript out of bounds

### ISSUE THREAD

**Issue by ktiu** [r-lib/crayon#110] opened 2021-02-02 11:08 UTC
In any of my terminals (iTerm with or without tmux, Terminal on Mac), when I executed 

```
> crayon::num_colors(TRUE)
```

I got the error message

```
Error in clienv$num_colors[[std]] : subscript out of bounds
```

This also prevented me from loading tidyverse in my terminal, which was a major problem.

I looked at the [code in question](https://github.com/r-lib/crayon/blob/e7f89c028f69fd92eb18fffb62ab0f1a947949f4/R/aab-num-ansi-colors.R#L91) and so in my ~/.Rprofile I added 

```
options(
  cli.num_colors=256L
)
```

This works now, but it took some digging.

For reference, `Sys.getenv("TERM")` outputs `screen-256color` or `xterm-256color`, respectively.

**Comment by gaborcsardi** [comment] 2021-02-02 12:22
Duplicate of #109.

**Closed by gaborcsardi** 2021-02-02 12:22 UTC
